import Anthropic from "@anthropic-ai/sdk";
import { prisma } from "@/lib/db";
import { parsePlan, validatePlan, type LlmPlan } from "./llm-selector";
import { persistSelection } from "./run";
import {
  buildRefinementPrompt,
  buildStartingDraft,
  extractChangeSummary,
  planToSelections,
  type RefinementDraft,
} from "./refine-plan";
import type { CandidateSegment } from "./types";

// The I/O half of conversational refinement. All the pure logic (prompt
// assembly, draft reconstruction, plan mapping, diffing) lives in
// refine-plan.ts so it can be unit-tested without a database or an API key.
export type {
  RefinementDraft,
  RefinementTurn,
  SelectionDiffEntry,
} from "./refine-plan";
export { diffSelections } from "./refine-plan";

// Same model/budget as the cold-start selector: refinement sends a much
// smaller prompt (no vision pass, no heuristic pre-filter — just the
// already-computed shortlist), but the response shape and its failure modes
// are identical.
const MODEL = "claude-sonnet-5";
const MAX_RESPONSE_TOKENS = 16000;

async function requestRefinementPlan(
  client: Anthropic,
  prompt: string,
): Promise<{ plan: LlmPlan; changeSummary: string }> {
  const message = await client.messages.create({
    model: MODEL,
    max_tokens: MAX_RESPONSE_TOKENS,
    messages: [{ role: "user", content: prompt }],
  });

  const textBlock = message.content.find((block) => block.type === "text");
  if (!textBlock || textBlock.type !== "text") {
    throw new Error(
      `Refinement response contained no text block. ` +
        `stop_reason=${message.stop_reason}, blocks=[${message.content.map((b) => b.type).join(",")}]`,
    );
  }
  if (message.stop_reason === "max_tokens") {
    throw new Error(
      "Refinement response was cut off at the token limit before finishing its JSON.",
    );
  }

  return {
    plan: parsePlan(textBlock.text),
    changeSummary: extractChangeSummary(textBlock.text),
  };
}

/**
 * Applies one natural-language instruction to the project's current cut (or
 * to its pending draft, if a conversation is already under way) and stores
 * the outcome as the new draft — whether it succeeded or not.
 *
 * A validation failure is a conversation turn the user can read and respond
 * to, not a thrown error: "make the opening longer" legitimately collides
 * with the 3-second hook rule, and that is a normal outcome here, unlike a
 * cold-start selection run which has nothing to fall back to. The failed
 * turn is recorded and the draft's cut is left exactly as it was.
 */
export async function refineSelection(
  projectId: string,
  instruction: string,
): Promise<RefinementDraft> {
  const apiKey = process.env.ANTHROPIC_API_KEY;
  if (!apiKey) {
    throw new Error(
      "ANTHROPIC_API_KEY is not set. Conversational refinement needs an Anthropic API key — see CLAUDE.md.",
    );
  }
  const client = new Anthropic({ apiKey });

  const project = await prisma.project.findUniqueOrThrow({
    where: { id: projectId },
    include: { selections: { orderBy: { order: "asc" } } },
  });

  // Refinement draws replacements from the shortlist the original cut was
  // chosen from — no new vision analysis, no ffmpeg, no candidate rebuild.
  // A heuristic-selector project has no shortlist and so cannot be refined.
  if (!project.selectionShortlistJson) {
    throw new Error(
      "This project's cut has no candidate shortlist to refine against — refinement needs a cut generated by the LLM selector.",
    );
  }
  const shortlist = JSON.parse(project.selectionShortlistJson) as CandidateSegment[];

  const startingDraft = buildStartingDraft(project, shortlist);
  const prompt = buildRefinementPrompt(startingDraft, shortlist, instruction);
  const at = new Date().toISOString();

  /** Keeps the previous cut and records why this turn didn't change anything. */
  const rejected = (reason: string): RefinementDraft => ({
    result: startingDraft.result,
    turns: [...startingDraft.turns, { instruction, response: reason, ok: false, at }],
  });

  let draft: RefinementDraft;
  try {
    let { plan, changeSummary } = await requestRefinementPlan(client, prompt);
    let validation = validatePlan(plan, shortlist);

    // Same single-retry-with-reason pattern the cold-start selector uses.
    if (!validation.ok) {
      const retryPrompt = `${prompt}\n\nהניסיון הקודם שלך נדחה: ${validation.reason}\nתקן את התוכנית כך שתעמוד בכללים ונסה שוב.`;
      ({ plan, changeSummary } = await requestRefinementPlan(client, retryPrompt));
      validation = validatePlan(plan, shortlist);
    }

    draft = validation.ok
      ? {
          result: {
            selections: planToSelections(plan, shortlist),
            premise: plan.premise,
            beatPlan: plan.beatPlan,
            shortlist,
          },
          turns: [
            ...startingDraft.turns,
            { instruction, response: changeSummary || plan.premise, ok: true, at },
          ],
        }
      : rejected(validation.reason);
  } catch (error) {
    // An instruction that contradicts the editing rules (e.g. "make the
    // opening 9 seconds" against the 3-second hook window) can make the
    // model spend its entire token budget reasoning and return only a
    // thinking block — observed in testing as a 4.5-minute request that
    // then 500'd. From the user's point of view that is still just "it
    // couldn't do what I asked", so it belongs in the conversation rather
    // than as an unhandled error. Same for a malformed-JSON response or a
    // transport failure.
    const message = error instanceof Error ? error.message : String(error);
    draft = rejected(
      `לא הצלחתי לבצע את ההוראה הזו — ייתכן שהיא מתנגשת עם כללי העריכה (למשל הוק של עד 3 שניות) או שאין חומר מתאים. נסה לנסח אותה אחרת. (${message})`,
    );
  }

  await prisma.project.update({
    where: { id: projectId },
    data: { refinementDraftJson: JSON.stringify(draft) },
  });

  return draft;
}

/** Makes a pending draft the project's live cut, via the same persistence path a selection run or profile-preview apply uses (which also clears the draft). */
export async function applyRefinementDraft(projectId: string): Promise<void> {
  const project = await prisma.project.findUniqueOrThrow({ where: { id: projectId } });
  if (!project.refinementDraftJson) {
    throw new Error("No pending refinement to apply.");
  }
  const draft = JSON.parse(project.refinementDraftJson) as RefinementDraft;
  await persistSelection(projectId, project.outputProfile, draft.result);
}

/** Throws the draft away. Never touches the live `Selection` rows. */
export async function discardRefinementDraft(projectId: string): Promise<void> {
  await prisma.project.update({
    where: { id: projectId },
    data: { refinementDraftJson: null },
  });
}
